import { contextBridge, ipcRenderer } from 'electron';
import type { ScribeAPI, Command } from '../shared/contracts';
const api: ScribeAPI = {
  getUpdateState:()=>ipcRenderer.invoke('updates:state'),
  checkForUpdates:()=>ipcRenderer.invoke('updates:check'),
  downloadUpdate:()=>ipcRenderer.invoke('updates:download'),
  installUpdate:()=>ipcRenderer.invoke('updates:install'),
  onUpdateState:handler=>{const fn=(_:unknown,value:import('../shared/updates').UpdateState)=>handler(value);ipcRenderer.on('updates:state',fn);return()=>ipcRenderer.removeListener('updates:state',fn);},
  listModels:()=>ipcRenderer.invoke('llm:models'),
  proofread:(text,mode)=>ipcRenderer.invoke('llm:proofread',text,mode),
  cancelProofread:()=>ipcRenderer.invoke('llm:cancel'),
  saveApiKey:key=>ipcRenderer.invoke('llm:key-save',key),
  hasApiKey:()=>ipcRenderer.invoke('llm:key-has'),
  getSettings:()=>ipcRenderer.invoke('settings:get'),
  saveSettings:s=>ipcRenderer.invoke('settings:save',s),
  rememberCorrection:(from,to)=>ipcRenderer.invoke('correction:remember',from,to),
  getHistory:()=>ipcRenderer.invoke('history:get'),
  addHistory:(text,source,details)=>ipcRenderer.invoke('history:add',text,source,details),
  updateHistory:(id,text,details)=>ipcRenderer.invoke('history:update',id,text,details),
  clearHistory:()=>ipcRenderer.invoke('history:clear'),
  deliver:(text,target,enter)=>ipcRenderer.invoke('deliver',text,target,enter),
  copy:text=>ipcRenderer.invoke('copy',text),
  saveText:text=>ipcRenderer.invoke('text:save',text),
  saveSubtitles:(segments,format,name)=>ipcRenderer.invoke('subtitles:save',segments,format,name),
  diarize:pcm=>ipcRenderer.invoke('speakers:run',pcm),
  cancelDiarization:()=>ipcRenderer.invoke('speakers:cancel'),
  onDiarizationProgress:handler=>{const fn=(_:unknown,value:import('../shared/speakers').SpeakerProgress)=>handler(value);ipcRenderer.on('speakers:progress',fn);return()=>ipcRenderer.removeListener('speakers:progress',fn);},
  pickAudio:()=>ipcRenderer.invoke('audio:pick'),
  status:value=>ipcRenderer.send('status',value),
  hide:()=>ipcRenderer.send('hide'),
  onCommand:handler=>{const fn=(_:unknown,cmd:Command)=>handler(cmd);ipcRenderer.on('command',fn);return()=>ipcRenderer.removeListener('command',fn);},
  cacheGet:async key=>{const data=await ipcRenderer.invoke('cache:get',key);return data ? new Uint8Array(data).buffer : null;},
  cacheHas:key=>ipcRenderer.invoke('cache:has',key),
  cachePut:(key,data)=>ipcRenderer.invoke('cache:put',key,data),
  getAppInfo:()=>ipcRenderer.invoke('app:info'),
};
contextBridge.exposeInMainWorld('scribe',api);
